export const G20_COUNTRY_DATA: string[] = [
     'Argentina' ,
     'Australia' ,
     'Brazil' ,
     'Canada' ,
     'China' ,
     'France' ,
     'Germany' ,
     'India' ,
     'Indonesia' ,
     'Italy' ,
     'Japan' ,
     'Mexico' ,
     'Russia' ,
     'Saudi Arabia' ,
     'South Africa' ,
     'South Korea' ,
     'Turkey' ,
     'United Kingdom' ,
     'USA-United States' ,
     'Hong Kong' ,
     'Singapore',
];
